### ISSUE TITLE
get a 404 error

### ISSUE THREAD

**Issue by tianheg** [dockwarder/julius#3]
your site source url should change

**Comment by tianheg** [comment]
![IMG_20201127_143535](https://user-images.githubusercontent.com/52186032/100418612-0920dc00-30be-11eb-8ffa-3dc6a09d28a5.jpg)

**Comment by dockwarder** [comment]
What do you mean specifically? On julius.dev "Source" points to the new repo at https://github.com/dockwarder/julius.dev. Is it that what you meant?

Thank you for taking the time to open an issue!

**Comment by tianheg** [comment]
Yes!
